### ISSUE TITLE
Не ставиться на Debian 7.0

### ISSUE THREAD

**Issue by happyalexkg** [sarutobi/Rynda#20]
При установке на Debian 7.0 x64 
при запуске bash createdb.sh
django.core.exceptions.ImproperlyConfigured: The pysqlite library does not support C extension loading. Both SQLite and pysqlite must be configured to allow the loading of extensions to use SpatiaLite.

**Comment by sarutobi** [comment]
покажите пожалуйста вывод spatialite --version. Разработка ведется на дебиан  7 x64, spatialite 4.1.1

**Comment by happyalexkg** [comment]
Package: spatialite-bin
Versions:
3.0.0~beta20110817-3+deb7u1 

root@pomosh:~# apt-cache showpkg libspatialite3
Package: libspatialite3
Versions:
3.0.0~beta20110817-3+deb7u1

**Comment by sarutobi** [comment]
Похоже, это баг  пакета в дебиане. Для исправления попробуйте воспользоваться вот этими рекомендациями официальной документации:
If you’ve decided to use a newer version of pysqlite2 instead of the sqlite3 Python stdlib module, then you need to make sure it can load external extensions (i.e. the required enable_load_extension method is available so SpatiaLite can be loaded).

This might involve building it yourself. For this, download pysqlite2 2.6, and untar:

$ wget https://pypi.python.org/packages/source/p/pysqlite/pysqlite-2.6.3.tar.gz
$ tar xzf pysqlite-2.6.3.tar.gz
$ cd pysqlite-2.6.3

Next, use a text editor to edit the setup.cfg file to look like the following:

[build_ext]
#define=
include_dirs=/usr/local/include
library_dirs=/usr/local/lib
libraries=sqlite3
#define=SQLITE_OMIT_LOAD_EXTENSION

https://docs.djangoproject.com/en/1.7/ref/contrib/gis/install/spatialite/#pysqlite2

**Comment by happyalexkg** [comment]
спасибо это помогло
но теперь при использовании апача
[Mon Jan 12 03:17:18.150435 2015] [wsgi:error] [pid 18470] [remote 212.42.102.61:512] mod_wsgi (pid=18470): Target WSGI script '/var/www/Rynda/rynda/Rynda/wsgi.py' cannot be loaded as Python module.
[Mon Jan 12 03:17:18.150513 2015] [wsgi:error] [pid 18470] [remote 212.42.102.61:512] mod_wsgi (pid=18470): Exception occurred processing WSGI script '/var/www/Rynda/rynda/Rynda/wsgi.py'.

**Comment by sarutobi** [comment]
Внес  изменения. Обновите проект командой git pull и рестартуйте апач.

**Comment by happyalexkg** [comment]
Добрый день
Прошу прощения за долгий ответ
установил все новой
но ошибка осталась
[Thu Jan 22 01:55:28 2015] [error] [client 212.42.102.61] mod_wsgi (pid=21190): Target WSGI script '/var/www/Rynda/rynda/Rynda/wsgi.py' cannot be loaded as Python module.
[Thu Jan 22 01:55:28 2015] [error] [client 212.42.102.61] mod_wsgi (pid=21190): Exception occurred processing WSGI script '/var/www/Rynda/rynda/Rynda/wsgi.py'.
[Thu Jan 22 01:55:28 2015] [error] [client 212.42.102.61] Traceback (most recent call last):

**Comment by sarutobi** [comment]
Добрый день!

Обновите проект командой git pull
перейдите в каталог rynda/Rynda/settings
создайте в нем файл local_stage.py и впишите в него следующее:
STATIC_ROOT = "/path/to/static/files/"
где "/path/to/static/files/" - путь к папке, куда будут собраны файлы статики (картинки, стили, скрипты) Подробнее http://rynda.readthedocs.org/ru/latest/production.html

Сообщите пожалуйста результат.

**Comment by happyalexkg** [comment]
Добрый день
сделал 
git pull

local_stage.py файла нет 

есть отдельно
local.py
stage.py

так же при запуске

 ./manage.py collectstatic
SpatiaLite version ..: 3.0.0-beta       Supported Extensions:
        - 'VirtualShape'        [direct Shapefile access]
        - 'VirtualDbf'          [direct Dbf access]
        - 'VirtualText'         [direct CSV/TXT access]
        - 'VirtualXL'           [direct XLS access]
        - 'VirtualText'         [direct CSV/TXT access]
        - 'VirtualNetwork'      [Dijkstra shortest path]
        - 'RTree'               [Spatial Index - R*Tree]
        - 'MbrCache'            [Spatial Index - MBR cache]
        - 'VirtualSpatialIndex' [R*Tree metahandler]
        - 'VirtualFDO'          [FDO-OGR interoperability]
        - 'SpatiaLite'          [Spatial SQL - OGC]
PROJ.4 Rel. 4.7.1, 23 September 2009
GEOS version 3.3.3-CAPI-1.7.4
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/rynda/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/var/www/rynda/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/rynda/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/var/www/rynda/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 42, in load_command_class
    return module.Command()
  File "/var/www/rynda/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 58, in __init__
    self.storage.path('')
  File "/var/www/rynda/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 45, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.


видимо это связанные ошибка

**Comment by sarutobi** [comment]
файл local_stage.py Вам нужно создать - он будет содержать настройки, специфичные для конкретно Вашего проекта.
в созданном файле local_stage.py нужно вписать путь к папке со статическими файлами (который у Вас указан в конфигурации апача, если Вы смотрели ссылку на инструкцию), формат:
STATIC_ROOT = "скопируйте путь сюда"

**Comment by happyalexkg** [comment]
Спасибо!
ДОбрался до новой ошибки
ttributeError at /
'module' object has no attribute 'GeoSQLCompiler'
Request Method:	GET
Request URL:	http://176.126.167.138/
Django Version:	1.7.1
Exception Type:	AttributeError
Exception Value:	
'module' object has no attribute 'GeoSQLCompiler'
Exception Location:	/var/www/rynda/lib/python2.7/site-packages/django/db/backends/__init__.py in compiler, line 1088
Python Executable:	/usr/bin/python
Python Version:	2.7.3
Python Path:	
['/var/www/rynda/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/var/www/rynda/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/var/www/Rynda',
 '/var/www/rynda/lib/python2.7/site-packages',
 '/var/www/rynda/lib/python2.7',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Птн, 23 Янв 2015 11:39:20 +0300

**Comment by sarutobi** [comment]
Вынес в новое замечание.
